on: push
name: Jira Issue Creation Demo
jobs:
  jiraIssueCreation:
    name: Jira Issue Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Jira Creation Demo
        uses: bryannice/gitactions-jira-issue-creation@master
        env:
          JIRA_ACCOUNT_URL: https://ld-appdev.atlassian.net/
          JIRA_API_TOKEN: uJUnvuoYt3fl2xzmofLW18AF
          JIRA_ISSUE_DESCRIPTION: Demoing Jira Issue Creation
          JIRA_ISSUE_SUMMARY: Demoing Jira Issue Creation
          JIRA_ISSUE_TYPE: Demoing Jira Issue Creation
          JIRA_PROJECT: DAI
          JIRA_USERNAME: loic.diridollou@gmail.com