on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        pylint ./application/*.py
    - name : Test with pytest
      run: |
        python -m pytest ./tests/
    - name: Login
      uses: atlassian/gajira-login@master
      if: always()
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Create
      id: create_fail
      uses: atlassian/gajira-create@master
      if: failure()
      with:
        project: DAI
        issuetype: Task
        summary: |
          Build failed for ${{ github.repository }}
        description: |
          Comparegtrwhvtr
    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      if: success()
      with:
        project: DAI
        issuetype: Task
        summary: |
          Build completed for ${{ github.repository }}
        description: |
          Comparegtrwhvtr