on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Complete CI/CD pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    name: Complete CI/CD pipeline
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        pylint ./application/*.py
    - name : Test with pytest
      env: 
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python -m pytest ./tests/
    - name: Deploying to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      if: success()
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ld-heroku
        heroku_email: loic.diridollou@gmail.com
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      if: failure()
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: Create issue if build fails
      id: create_fail
      uses: atlassian/gajira-create@master
      if: failure()
      with:
        project: DAI
        issuetype: Task
        summary: |
          CI/CD failed for ${{ github.repository }}
        description: |
          Comparegtrwhvtr